2024-12-18 21:14:59,472 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "/home/ed/PycharmProjects/MyPython24/module_12/lesson_12/tests_12_4.py", line 24, in test_run
    second = Runner(int)
  File "/home/ed/PycharmProjects/MyPython24/module_12/lesson_12/rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано type
2024-12-18 21:14:59,473 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "/home/ed/PycharmProjects/MyPython24/module_12/lesson_12/tests_12_4.py", line 13, in test_walk
    first = Runner("Клод", -5) # speed: 5 (for выполнен успешно)
  File "/home/ed/PycharmProjects/MyPython24/module_12/lesson_12/rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
